import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import {
  designTokensToCssRoot, designTokensToCssVariables, flattenDesignTokens,
  tokenPathToCssVariable,
} from '../src/design-token-css.js';

const generatedCss = readFileSync(new URL('../src/generated/design-tokens.css', import.meta.url), 'utf8');
const moduleSource = readFileSync(new URL('../src/design-token-css.js', import.meta.url), 'utf8');

test('designTokensToCssRoot emits deterministic :root CSS variables', () => {
  const css = designTokensToCssRoot();
  assert.match(css, /^:root \{/);
  assert.match(css, /--lpt-color-surface-canvas/);
  assert.match(css, /--lpt-color-text-primary/);
  assert.match(css, /--lpt-color-accent-progress/);
  assert.match(css, /--lpt-space-xl/);
  assert.match(css, /--lpt-radius-card/);
  assert.match(css, /--lpt-effect-lead-glow/);
  assert.match(css, /--lpt-motion-duration-base/);
  assert.equal(css, designTokensToCssRoot());
});

test('token path helpers flatten readable names and theme objects', () => {
  assert.equal(tokenPathToCssVariable(['color', 'surface', 'canvas']), '--lpt-color-surface-canvas');
  assert.equal(tokenPathToCssVariable(['spacing', 'xl']), '--lpt-space-xl');
  assert.ok(flattenDesignTokens().some(entry => entry.path.join('.') === 'color.surface.canvas'));
  assert.ok(designTokensToCssVariables().some(entry => entry.name === '--lpt-color-accent-progress'));
  assert.ok(designTokensToCssVariables().some(entry => entry.name === '--lpt-effect-lead-glow'));
});

test('generated CSS file exists and matches generator output', () => {
  const expected = '/* Generated by scripts/generate-design-token-css.mjs. Do not edit by hand. */\n'
    + designTokensToCssRoot();
  assert.equal(generatedCss, expected);
});

test('generated CSS includes the Aurora palette and effect tokens', () => {
  assert.match(generatedCss, /--lpt-color-surface-canvas: #15131C;/);
  assert.match(generatedCss, /--lpt-color-text-primary: #F2EFF7;/);
  assert.match(generatedCss, /--lpt-color-text-secondary: #ABA3B8;/);
  assert.match(generatedCss, /--lpt-color-text-muted: #958CA5;/);
  assert.match(generatedCss, /--lpt-color-accent-progress: #6D5DF6;/);
  assert.match(generatedCss, /--lpt-color-tier-perfect: #B15CF6;/);
  assert.match(generatedCss, /--lpt-effect-lead-glow: 0 8px 24px rgba\(109, 93, 246, 0\.42\);/);
  assert.doesNotMatch(generatedCss, /--lpt-color-accent-progress: #d8b24c;/);
  assert.doesNotMatch(generatedCss, /--lpt-color-accent-progress: #3b82f6;/);
  assert.doesNotMatch(generatedCss, /--lpt-color-tier-passed: #3b82f6;/);
});

test('design token CSS module has no DOM, Firebase, analytics, server or env imports', () => {
  assert.doesNotMatch(moduleSource, /from ['"].*(firebase|analytics|server|api\/_lib|db\.js|auth\.js)/);
  assert.doesNotMatch(moduleSource, /document|window|localStorage|process\.env|import\.meta\.env/);
});
