/* All schedule, ladder, drill & resource data. */
export const R = {
  bt:{l:'Bright Trip - Visual Storytelling (Harris + Nathaniel Drew)', u:'https://www.brighttrip.com/courses/visual-storytelling'},
  hiw:{l:'How I Write - Johnny Harris (full interview)', u:'https://www.youtube.com/watch?v=zq4b96m1AvM'},
  ss5:{l:'Skillshare - Story through Film: the 5 Acts', u:'https://www.skillshare.com/en/classes/storytelling-through-film-how-to-create-engaging-videos-for-youtube/1022218532'},
  ssm:{l:'Skillshare - Storytelling Masterclass: make viewers care', u:'https://www.skillshare.com/en/classes/storytelling-masterclass-for-video-creators-how-to-make-viewers-care/88147891'},
  som:{l:'School of Motion - motion design & composition (After Effects)', u:'https://www.schoolofmotion.com'},
  bguru:{l:'Blender Guru - lighting, camera & composition in Blender', u:'https://www.youtube.com/@blenderguru'},
  efap:{l:'Every Frame a Painting - composition & visual storytelling', u:'https://www.youtube.com/@everyframeapainting'},
  epi:{l:'Epidemic Sound - music & SFX library (+ their tutorials)', u:'https://www.epidemicsound.com'},
  swc:{l:'SoundWorks Collection - how pro films are sound-designed (study the masters)', u:'https://www.soundworkscollection.com'},
  filmsound:{l:'FilmSound.org - the craft & theory of sound in film', u:'http://filmsound.org'},
  mmcgee:{l:'Marshall McGee (YouTube) - clear, practical sound-design technique', u:'https://www.youtube.com/channel/UCIoNgwHpavUi2UnC68cKgbw'},
  asfx:{l:'A Sound Effect - deep-dive articles, interviews & SFX', u:'https://www.asoundeffect.com'},
  pse:{l:'Pro Sound Effects - Learn (sound editing guides)', u:'https://blog.prosoundeffects.com'},
  csound:{l:'Coursera - Sound Design courses (structured, Berklee et al.)', u:'https://www.coursera.org/courses?query=sound%20design'},
  freesound:{l:'Freesound - free SFX to build libraries & practice', u:'https://freesound.org'},
  jh:{l:'Study: Johnny Harris channel (visual anchors, structure)', u:'https://www.youtube.com/@johnnyharris'},
  fern:{l:'Study: Fern channel (armchair documentaries)', u:'https://www.youtube.com/@fern-tv'},
  yarn:{l:'Study: Yarnhub channel (3D historical animation)', u:'https://www.youtube.com/@Yarnhub'},
  k20:{l:'The First 20 Hours - Josh Kaufman (rapid skill method)', u:'https://youtu.be/5MgBikgcWnY'},
  peak:{l:'Peak - Anders Ericsson (deliberate practice, the source)', u:'https://www.goodreads.com/book/show/26312997-peak'},
  blender:{l:'Blender - official + manual', u:'https://www.blender.org'},
  casc:{l:'Cascadeur - physics-based AI posing', u:'https://cascadeur.com'},
  plask:{l:'Plask - AI motion capture to Blender', u:'https://plask.ai'},
  deep:{l:'DeepMotion - AI motion capture', u:'https://www.deepmotion.com'},
  meshy:{l:'Meshy - text / image to 3D assets', u:'https://www.meshy.ai'},
  tripo:{l:'Tripo - text / image to 3D assets', u:'https://www.tripo3d.ai'},
  real:{l:'Reallusion - iClone + Character Creator (the Yarnhub stack)', u:'https://www.reallusion.com'},
  yarn80:{l:'Yarnhub pipeline breakdown (80.lv interview)', u:'https://80.lv/articles/the-yarnhub-team-talks-using-reallusion-s-iclone-character-creator-to-set-up-historic-animations'},
};
export const QDEF = {
  1:{name:'Q1 · Story + Visual Direction', sub:'The foundation that multiplies everything', wed:'Visual warm-up - composition & lighting study'},
  2:{name:'Q2 · 3D Cinematic Craft', sub:'Your differentiator - environments, camera, mocap', wed:'3D craft block'},
  3:{name:'Q3 · Integration', sub:'One ambitious original - prove you can do it all', wed:'Integration build - this week task'},
  4:{name:'Q4 · Voice + Mastery', sub:'Stop imitating. Become recognisably you.', wed:'Centerpiece / signature-voice work'},
};
export const WEEKS = [
  {w:1,q:1,focus:'Foundations & the deliberate-practice engine. Set your start date and define your target performance level.',res:[R.k20,R.hiw]},
  {w:2,q:1,focus:'Story structure on paper - three acts, curiosity loops, and the "promise".',res:[R.bt,R.hiw]},
  {w:3,q:1,focus:'Show, dont tell - visual anchors and the 5-act beat map.',res:[R.bt,R.ss5]},
  {w:4,q:1,focus:'Cold opens & hooks - land the viewer in under 6 seconds.',res:[R.ss5,R.ssm],ms:'Mini-ship: your first 30-sec shot-for-shot recreation of a master.'},
  {w:5,q:1,focus:'Composition - framing, balance, leading the eye. Drill it in both After Effects and Blender.',res:[R.efap,R.som,R.bguru]},
  {w:6,q:1,focus:'Cinematic lighting fundamentals - the one-frame lighting drill.',res:[R.bt,R.bguru]},
  {w:7,q:1,focus:'Colour & mood - palettes that carry emotion.',res:[R.jh,R.fern]},
  {w:8,q:1,focus:'Camera language - moves, motivation, easing.',res:[R.efap,R.jh]},
  {w:9,q:1,focus:'Pacing & rhythm - cutting to the beat.',res:[R.ssm,R.efap]},
  {w:10,q:1,focus:'Sound design layer - build a full bed from scratch (ambience, FX, music).',res:[R.swc,R.mmcgee,R.epi]},
  {w:11,q:1,focus:'Packaging mastery - title, thumbnail, and paying off the promise.',res:[R.hiw,R.jh]},
  {w:12,q:1,focus:'Milestone week - consolidate Q1 into one finished original.',res:[R.fern,R.jh],ms:'SHIP: a 60-90s original cinematic short. Hook must land in under 6s.'},
  {w:13,q:2,focus:'Blender cinematic cameras - lensing, depth of field, motivated moves.',wed:'Cinematic cameras in Blender',res:[R.blender,R.bguru]},
  {w:14,q:2,focus:'Blender lighting & look-dev - mood, contrast, atmosphere.',wed:'Lighting & look-dev',res:[R.blender,R.bguru]},
  {w:15,q:2,focus:'Environment art - one finished cinematic frame in a single block.',wed:'Environment to one finished frame',res:[R.blender,R.meshy]},
  {w:16,q:2,focus:'Kitbashing & set dressing using AI-generated assets.',wed:'Kitbash & set dressing',res:[R.meshy,R.tripo]},
  {w:17,q:2,focus:'Materials & texturing for believable realism.',wed:'Materials & texturing',res:[R.blender]},
  {w:18,q:2,focus:'Choose your character route - study the Yarnhub pipeline and decide.',wed:'Character pipeline decision: Blender+mocap vs iClone/CC',res:[R.yarn80,R.real]},
  {w:19,q:2,focus:'AI motion capture into Blender (Plask / DeepMotion).',wed:'Mocap capture to cleanup on your rig',res:[R.plask,R.deep]},
  {w:20,q:2,focus:'Physics-based posing with Cascadeur for action beats.',wed:'Cascadeur action beats',res:[R.casc]},
  {w:21,q:2,focus:'Character acting - one emotion per rep.',wed:'Character beats, one emotion each',res:[R.casc,R.yarn]},
  {w:22,q:2,focus:'Camera animation on 3D - parallax reveals, orbits, push-ins.',wed:'3D camera moves + easing',res:[R.blender,R.efap]},
  {w:23,q:2,focus:'Rendering & compositing inside Blender.',wed:'Render + comp pass',res:[R.blender]},
  {w:24,q:2,focus:'Milestone week - assemble your 3D sequence.',wed:'Final shot-sequence assembly',res:[R.yarn],ms:'SHIP: a 60s 3D-heavy sequence - environment + moving camera + one character beat, fully lit & graded.'},
  {w:25,q:3,focus:'Pick the topic + deep research (the Fern method).',res:[R.fern]},
  {w:26,q:3,focus:'Script + visual direction - color-coded margins, Harris-style.',res:[R.hiw]},
  {w:27,q:3,focus:'Storyboard / previz - a motion storyboard (AI video as previz).',res:[R.jh]},
  {w:28,q:3,focus:'Asset & environment build for the piece.',res:[R.meshy,R.blender]},
  {w:29,q:3,focus:'3D reenactment shots.',res:[R.casc,R.plask]},
  {w:30,q:3,focus:'Maps & infographics (GeoLayers / After Effects).',res:[R.jh,R.som]},
  {w:31,q:3,focus:'Animation pass across the piece.',res:[R.casc]},
  {w:32,q:3,focus:'Lighting & render pass.',res:[R.blender,R.bguru]},
  {w:33,q:3,focus:'Edit assembly - story first, then b-roll.',res:[R.bt]},
  {w:34,q:3,focus:'Sound design + music - full mix to broadcast.',res:[R.filmsound,R.epi]},
  {w:35,q:3,focus:'Colour grade & final polish.',res:[R.blender]},
  {w:36,q:3,focus:'Milestone week - finish and run the blind test.',res:[R.fern,R.yarn],ms:'SHIP: a 3-minute original cinematic documentary. Run the blind test against a Fern/Yarnhub clip.'},
  {w:37,q:4,focus:'Visual voice audit - define your palette and motion language.',res:[R.fern,R.jh]},
  {w:38,q:4,focus:'Develop your signature motion language.',res:[R.yarn,R.efap]},
  {w:39,q:4,focus:'Packaging & thumbnail mastery for your own brand.',res:[R.hiw]},
  {w:40,q:4,focus:'Advanced compositing & FX.',res:[R.blender,R.som]},
  {w:41,q:4,focus:'Speed & efficiency - cut your time-to-finished-shot.',res:[R.k20]},
  {w:42,q:4,focus:'Centerpiece - concept + research.',res:[R.fern]},
  {w:43,q:4,focus:'Centerpiece - script + previz.',res:[R.hiw]},
  {w:44,q:4,focus:'Centerpiece - build.',res:[R.blender,R.meshy]},
  {w:45,q:4,focus:'Centerpiece - animation & render.',res:[R.casc,R.blender]},
  {w:46,q:4,focus:'Centerpiece - edit & sound.',res:[R.ssm,R.epi]},
  {w:47,q:4,focus:'Centerpiece - grade, polish & public launch.',res:[R.jh]},
  {w:48,q:4,focus:'Milestone week - ship the centerpiece and write the year-one retro.',res:[R.peak],ms:'SHIP: your portfolio centerpiece in your own voice. Write the retro & plan the next arc.'},
];
export const DAY_TPL = [
  {k:'mon',n:'Mon',l:'Story / script drill',s:'Deconstruct a masters structure; write a hook + cold open.'},
  {k:'tue',n:'Tue',l:'Visual direction drill',s:'Recreate one master shot, then originate one with the same technique.'},
  {k:'wed',n:'Wed',l:'3D craft block',s:'The quarters technical focus.'},
  {k:'thu',n:'Thu',l:'Motion graphics / maps / explainer drill',s:'Animated map or kinetic stat with strict text hierarchy.'},
  {k:'fri',n:'Fri',l:'Edit + sound drill',s:'Assemble the weeks micro-piece; cut to the beat, build the mix.'},
  {k:'sat',n:'Sat',l:'SHIP - finish & publish one piece',s:'Post it for feedback. Shipping is the skill.',ship:true},
  {k:'sun',n:'Sun',l:'Retro + reference study',s:'Review your log, plan next week, study frame-by-frame.'},
];
export const COMP_LADDER = [
  ['Rule of thirds & the grid - place subjects with intent',''],
  ['Leading lines & eye-path - guide the viewer through the frame',''],
  ['Balance & negative space - weight, tension, breathing room',''],
  ['Depth & layering - foreground / midground / background',''],
  ['Frame-in-frame & framing devices',''],
  ['Scale & dominance - establish hierarchy in one glance',''],
  ['Composition in motion - hold balance as elements move','AE'],
  ['Lower-thirds & on-screen text composition (your video rules)','AE'],
  ['Camera blocking & staging - composing a 3D shot','Blender'],
  ['Depth via lens, DOF & atmosphere','Blender'],
  ['Composition that serves the story - every frame earns its place',''],
];
export const SOUND_LADDER = [
  ['Active listening - break a master mix into its layers',''],
  ['Ambience beds - build a space from atmos & room tone',''],
  ['Spot FX & foley - sync sound to action',''],
  ['Transitions - whooshes, risers, impacts that move the cut',''],
  ['Music selection - match track to the emotional beat',''],
  ['Editing music - cut to phrase, land on the downbeat',''],
  ['Levels & mixing - balance dialogue / music / FX',''],
  ['Ducking & sidechain - let narration breathe',''],
  ['Diegetic vs non-diegetic - design the soundworld',''],
  ['Emotional scoring - sound that makes viewers feel',''],
  ['Full mix to broadcast - LUFS, polish, deliver',''],
];
export const DRILLS = [
  {g:'A · Story / Script',items:[
    ['Cold-Open Factory','Write 5 cold opens a week. One becomes a produced piece. Hook must land in under 6 seconds.'],
    ['Structure Autopsy','Map a Fern/Harris videos three acts, every curiosity loop, and where the promise pays off. Rebuild that skeleton with your own topic.'],
    ['Scripting-while-directing','Write a script with color-coded visual direction in the margin - every line tagged with the shot or asset it needs.'],
  ]},
  {g:'B · Visual Direction',items:[
    ['Shot-for-Shot','Recreate 30s of a master sequence as closely as you can. Then make an original 30s with the same techniques.'],
    ['Visual Anchor Drill','For a real event, design 3 show-dont-tell frames that explain it with zero narration.'],
    ['One-Frame Lighting','Light a single still to a finished cinematic frame. Vary key/fill/rim; study the mood shift.'],
  ]},
  {g:'B+ · Composition (AE + Blender)',items:[
    ['Thirds & eye-path  [both]','Take 5 frames; recompose each on the thirds grid and draw the eye-path. Then build one original.'],
    ['Depth in 3 layers  [Blender]','Stage a shot with clear FG / MG / BG. Use DOF + atmosphere to separate the planes.'],
    ['Motion composition  [AE]','Animate 3 elements into frame keeping balance at every moment - composition that holds under movement.'],
    ['Lower-third & text comp  [AE]','Compose a readable lower-third + on-screen point per your rules: centered guides, clean hierarchy.'],
    ['Camera blocking  [Blender]','Block one cinematic shot - camera, lens, subject - for a frame that reads in 2 seconds.'],
  ]},
  {g:'C · 3D Craft (your weapon)',items:[
    ['One-Day Environment','Model + light + render one cinematic environment to a finished frame in a single block. Kitbash with AI assets to stay fast.'],
    ['Camera-Language Reps','Recreate one master camera move (push-in, parallax reveal, orbit) with correct easing.'],
    ['Mocap Beat','Capture a 5s performance (phone to AI mocap), clean it on your rig, light it, render it. One emotion per rep.'],
  ]},
  {g:'D · Motion Graphics / Maps',items:[
    ['Map Sprint','Build a Harris-style animated map for a real event in 2 hours (GeoLayers).'],
    ['Infographic-in-Motion','Turn one statistic into a 10s kinetic explainer - gold=metrics, red=warnings, green=solutions.'],
  ]},
  {g:'E · Edit',items:[
    ['Rhythm Pass','Re-cut an existing scene to a new track; match every hard cut to a transient.'],
    ['Story-first Assembly','Build the cut on story beats first; add b-roll only after the spine holds.'],
  ]},
  {g:'F · Sound Design',items:[
    ['Layer Autopsy','Take 15s of a master mix. Write down every layer: ambience, FX, foley, music, dialogue.'],
    ['Ambience Bed','Build a room/space from atmos + room tone only - no music.'],
    ['Spot FX & Foley','Sync sound to every action in a 10s clip.'],
    ['Transition Kit','Design 3 transitions (whoosh / riser / impact) that move a cut.'],
    ['Music-to-Beat','Cut a track to picture so downbeats land on your hardest cuts (Epidemic).'],
    ['Mix & Duck','Balance dialogue/music/FX; sidechain music under narration so it breathes.'],
  ]},
];
export const RES_GROUPS = [
  {g:'Storytelling (assigned across Q1)',items:[R.bt,R.hiw,R.ss5,R.ssm]},
  {g:'Composition - After Effects + Blender',items:[R.efap,R.som,R.bguru]},
  {g:'Sound design - learn & study',items:[R.swc,R.mmcgee,R.filmsound,R.asfx,R.pse,R.csound,R.freesound,R.epi]},
  {g:'Study these masters (frame-by-frame, daily)',items:[R.jh,R.fern,R.yarn]},
  {g:'3D craft & the 2026 tool stack',items:[R.blender,R.casc,R.plask,R.deep,R.meshy,R.tripo,R.real,R.yarn80]},
  {g:'The science (so you trust the method)',items:[R.k20,R.peak]},
];


/* ── SKILLS catalog ── add a new object here to publish another learning path. ── */
export const SKILLS = [
  {
    id: 'cinematic',
    title: 'Cinematic Storytelling \u00d7 3D',
    tagline: 'Good \u2192 world-class in one year',
    blurb: 'Master visual storytelling with 3D as your signature weapon - story, composition, 3D craft, motion graphics, and sound.',
    quarters: QDEF,
    plan: WEEKS,
    days: DAY_TPL,
    ladders: [
      { key: 'comp',  title: 'Composition (AE + Blender)', cap: 'Frame everything with intent, in both tools', rungs: COMP_LADDER },
      { key: 'sound', title: 'Sound Design', cap: 'From layered beds to a broadcast-ready emotional mix', rungs: SOUND_LADDER },
    ],
    drills: DRILLS,
    resources: RES_GROUPS,
  },
];
